# Generated by Django 3.2.7 on 2021-10-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StepOrder', models.IntegerField()),
                ('Step', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('PasswordHash', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Privacy', models.BooleanField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEditRecipe.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngredientName', models.CharField(max_length=50)),
                ('Unit', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('IngredientOrder', models.IntegerField()),
                ('RecipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateEditRecipe.recipe')),
            ],
        ),
    ]
