# Generated by Django 3.2.7 on 2021-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEditRecipe', '0002_auto_20211012_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
