# Generated by Django 3.2.7 on 2021-10-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEditRecipe', '0003_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='RecipeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CreateEditRecipe.recipe'),
            preserve_default=False,
        ),
    ]
