# Generated by Django 3.2.7 on 2021-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEditRecipe', '0004_step_recipeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='isSubStep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepOrder',
            field=models.FloatField(),
        ),
    ]
